# Generated by Django 6.0.6 on 2026-06-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                ("banco_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("fondos", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gastos",
            fields=[
                ("gasto_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_gasto", models.CharField(max_length=100)),
                ("detalle_gasto", models.TextField()),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("CANCELLED", "Cancelado"),
                            ("PAID", "Pagado"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.cliente"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                ("pago_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_pago", models.CharField(max_length=100)),
                ("detalle_pago", models.TextField()),
                ("monto_pago", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("CANCELLED", "Cancelado"),
                            ("PAID", "Pagado"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "banco_id",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.banco",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gasto_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.gastos"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimientos",
            fields=[
                (
                    "movimiento_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("fecha_movimiento", models.DateTimeField(auto_now_add=True)),
                ("pago", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monto_anterior",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monto_resultante",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "id_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pagos"
                    ),
                ),
            ],
        ),
    ]
