# Generated by Django 6.0.6 on 2026-06-12 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagos",
            name="banco_id",
            field=models.ForeignKey(
                default="1",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.banco",
            ),
        ),
    ]
