# Generated by Django 6.0.6 on 2026-06-12 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_pagos_banco_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetallePago",
            fields=[
                (
                    "detalle_pago_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_pago", models.DateField()),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.banco"
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pagos"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
